### ISSUE TITLE
Change json write mode to Append

### ISSUE THREAD

**Issue by Akhliskun** [mozilla-releng/firefox-infra-changelog#112]
As we stand right now, the script is always re-writing the entire JSON file that contains all the commits that we see. What we want is to have a full list of changes for each repository, so in this issue I will explain what exactly we need and how to make the implementation:

## Functionality needed:
When we run the script for the very first time
- Check if json files exist (they should not!)
- Introduce 2 new tracking variables named (as an example):
-- **last_repo_verified** = str(NAME-OF-REPO-HERE)
-- **last_page_verified** = int(HERE)
-- Those 2 need to be saved in a file. Maybe call it **constants.json** ?
- Write in append mode to the json files.

## Logic behind new functionality:

 - Script will check if it's for the first time it ever ran, for a specific repo. We will know this if the json for that specific repository exists or not.

 - If the first doesn't exist, run the script to ask for each page of commits (if I remember correctly, only 20 commits are returned per page)

 - If the file exists, ask for the commits since we last checked the repository (we already have the functionality)

**Comment by raduiman** [comment]
I have created the following diagram for a better explanation of my idea:

![append-mode-diagram](https://user-images.githubusercontent.com/35918050/50099678-5f751700-0227-11e9-8996-ff1d09dd8258.JPG)

Before to write the new commits into the .json file we need to append the old commits one by one.
'''
new_repo_dict = { new commits }
old_repo_dict =  { old commits }
repo_dict =new_repo_dict
for commit in old_repo_dict:
      repo_dict.append(old_repo_dict[commit])
'''

The method implemented by @mutterroland in PR #123 will work fine after a few changes mentioned above. I will try to implement it in my next PR.

**Comment by raduiman** [comment]
PR #140 fixed this issue on the GitHub side. The work remaining to here is to change the code for Mercurial in the same way.

**Comment by Akhliskun** [comment]
This was completed by Roli, in a PR which will come abit later.
