### ISSUE TITLE
Implement a method to push new changes to the github repository.

### ISSUE THREAD

**Issue by bccrisan** [mozilla-releng/firefox-infra-changelog#121]
### Implement a function/method that:
- Adds to a commit the modifications to the following files:
- - `git_files` folder
- - `hg_files` folder
- - `main_md_table.md`
- *Excludes* any modifications to the `script files` (any file that is part of the script/script configuration files, ex. `repositories.json`)
- Commits the changes with a commit message automatically generated and pushes the commit to the commit master.
- Creates a backup branch automatically (this would be a fail-safe/fall-back system in case things would go out of control)

This can be implemented in two ways:
- Using the Git API
- Using the git and executing bash-like commands from python (using os.system(`bashCommand`)

**Additional context**
The `os.system` method is deprecated and python 3.7 comes with default support for subprocess.
Doing something like:
`
p = subprocess.run(["git", "status"], stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=False)
`
and
`print(p)`

Outputs
`CompletedProcess(args=['git', 'status'], returncode=0, stdout=b'On branch master\nYour branch is up to date with \'origin/master\'.\n\nChanges to be committed:\n  (use "git reset HEAD <file>..." to unstage)\n\n\tnew file:   handle_git.py\n\tdeleted:  ...`
*Expected*

Done further testing with it and apart from not seeing the ssh agent, this would be an easy solution to push the new content back to github.

This is the only issue I have discovered with this *solution* at the moment.

**Comment by Akhliskun** [comment]
We don't need python subprocess, PyGitHub comes with its own helper functions to add/stage modified files, commit and push them using the same provided token.

**Comment by bccrisan** [comment]
### Continued to work on it and experimented a few things about this.

#### I have managed to:
 - add a specific file (git add file_name)
 - create a specific commit message (git commit -m "Specific text")
 - push the commits to remote branch (git push origin master)

#### Example [code](https://github.com/bccrisan/ciduty_tools/blob/master/testing_git_object.py) and [push commits](https://github.com/bccrisan/ciduty_tools/commits/master) (done from the script).

In the above example, the function [handle_git()](https://github.com/bccrisan/ciduty_tools/blob/master/testing_git_object.py#L23) will create a new repo object by calling `git.Repo.clone_from()` that takes 4 arguments:
 - `"https://github.com/bccrisan/ciduty_tools"` - remote link to the repository
 - `os.path.join(os.getcwd()` - os path using get current working directory and using join on it (I don't think that it's really necessary, needs further investigation/testing)
 - `"testing_ciduty_tools"` - local name of the repository 
- `branch='master'` - used for cloning the data from a specific branch. (in this case, the master branch)

On the [next lines of the code](https://github.com/bccrisan/ciduty_tools/blob/master/testing_git_object.py#L26) we initialize an empty repository because we'll need that empty repo later when we'll use it to create the origin object.

That `origin` object will be later used to fetch, pull and push data to the origin.
#### Workflow:
 - clone repo
 - create empty repository object
 - create origin object based on empty project
 - fetch and pull the origin.
 - `your code to be executed goes here`
 - add files to the **cloned repo** (using `repo.index.add([path_to_file])` )
 - create a commit message (using `repo.index.commit("Commit message")` )
 - use the `origin` object and call `push()` on it.

After the script finished doing the work, we need to call `os.system("rmdir /S /Q \"{}\"".format(path))` on it. This part of the script, makes sure that all of the files left behind are getting removed otherwise at the next run the script will fail due to git repository already exists.
#### Known issues with the code:
 - Not sure how the pushes are made, we need to see on a freshly installed machine how the code handles missing git configuration. Probably we need to make the code use the GIT_TOKEN.
 - As the script works at the moment, the repository folder we need to clone, modify files and push the changes, *cannot* exist. we need to check if we can set up the code to recognize the already cloned repository. If that cannot be done we will need to keep the two scripts in separated folders because I don't think we can have two `.git` folders in the same tree-style directory or update the same git files that are already opened by a program/script/process.
