### ISSUE TITLE
Configure all repositories to suit ciduty purposes 

### ISSUE THREAD

**Issue by zsoltfay** [mozilla-releng/firefox-infra-changelog#133]
We want each repository to be configured in a custom way, in accordance to what ciduty needs from each one.

- So far we have a list with every repository
- if we care about certain files from within a repository or we care about everything that it contains
- and how to determine what is live in production

Except for the 2 taskcluster repositories (taskcluster-auth,  taskcluster-queue). We know we should care about everything within these 2 repos, but we don't know if a new commit should be considered automatically in production.

**Comment by Akhliskun** [comment]
@zsoltfay Ask dustin about this.

**Comment by zsoltfay** [comment]
Taskcluster is now a large mono-repo. We track every commit that lands there.
