### ISSUE TITLE
Loophole through which we currently miss commits

### ISSUE THREAD

**Issue by zsoltfay** [mozilla-releng/firefox-infra-changelog#141]
The code right now updates the json files whenever a version bump happens, as long as the version from build-puppet and from within the changelog of said specific repo are different. 

However if both locations get updated before the script has a chance to run it won't realize we have new commits. We need a check that compares the latest live version of a repo to the one we have stored in our json files. And if these aren't equal we should get all the commits that we missed.

**Comment by raduiman** [comment]
This issue is fixed by commit [c58e2cdda96872af91270ee95cdd5f289864ba99](https://github.com/mozilla-releng/firefox-infra-changelog/commit/c58e2cdda96872af91270ee95cdd5f289864ba99).
