### ISSUE TITLE
Break the existing code in smaller functions

### ISSUE THREAD

**Issue by mutterroland** [mozilla-releng/firefox-infra-changelog#151]
Moving further with the development we have to break the existing code into smaller functions and separate the code into multiple dedicated files.

**Comment by zsoltfay** [comment]
After a little brainstorming I've been thinking of simplifying the biggest function we have by inverting the logic of the 3 for loops, thus ending with something like:
 For each commit > save all changed files into a list > take each scriptworker repo one by one and check if its respective

**Comment by zsoltfay** [comment]
The long functions have been trimmed down in PR #186
