### ISSUE TITLE
Write logic for -l flag

### ISSUE THREAD

**Issue by mutterroland** [mozilla-releng/firefox-infra-changelog#158]
# Request
We have to write and implement logic for -l flag.

# Implementation
LOG bool has been already added to configuration file. By passing -l flag when running the script ,it should print us useful data related to script. In this implementation, we should remove all log script currently prints by default and , eventually, add even more useful log information. 

### Important note : If we run the script without any arguments, it should still run normally without stopping. So , in the process, we still have to keep it running without arguments.

**Comment by raduiman** [comment]
I have started to work on this functionality so I'm going to assign this issue to me.  
My intention is to implement the logic for -l flag using the 'logging' module in python: https://docs.python.org/3/library/logging.html
https://realpython.com/python-logging/

**Comment by mutterroland** [comment]
Improved logging in #213
