### ISSUE TITLE
Write logic for -m flag

### ISSUE THREAD

**Issue by mutterroland** [mozilla-releng/firefox-infra-changelog#159]
# Request
We have to write and implement logic for -r flag.

# Implementation
This one will be a little bit more trickier as it requires more logic/ modifications to current logic to be implemented. By using -m flag, we should be able to update / generate MD tables only for repos we want to . As a suggestion , when using -m flag firstly it will display a list of all current available repos , waits for our input and runs the logic only for selected repos.

## Example:

```
$~python client.py -m


1. Ci-admin
2. Ci-configuration
3. Mozilla-central
4. Repo
5. Repo
.
.
n+1. Repo	

$~ 1, 2, 3
```
This should modify data only for Ci-admin, Ci-configuration, Mozilla-central.

**Comment by mutterroland** [comment]
I have already started working on this so I'm assigning this one to me.

**Comment by mutterroland** [comment]
#163

**Comment by mutterroland** [comment]
165

**Comment by mutterroland** [comment]
As #165 got merged, the only thing that remains to be done is logic for *script repos

**Comment by mutterroland** [comment]
@zsoltfay any updates here?

**Comment by zsoltfay** [comment]
PR #224 addresses this issue as well
