### ISSUE TITLE
Generate and replace bug numbers with bugzilla links in markdown files.

### ISSUE THREAD

**Issue by bccrisan** [mozilla-releng/firefox-infra-changelog#166]
In the commit description section from each markdown we have commits that include bug numbers, something like `Fix for bug 1234567, r=someone`.

We can replace `bug 1234567` with [bug 1234567](https://bugzilla.mozilla.org/show_bug.cgi?id=1234567)
so the final result to be something like:
"Fix for [bug 1234567](https://bugzilla.mozilla.org/show_bug.cgi?id=1234567), r=someone."

**Comment by Akhliskun** [comment]
Did we explore any options for this issue?
I believe this would be a great addition.

**Comment by mutterroland** [comment]
I've made some progress today and pushed changes on this branch(https://github.com/mozilla-releng/firefox-infra-changelog/tree/rmutter-wip-issue166) 
As it is still in progress ,# please do not merge# . It is safe to pull changes and continue to work on it.

For now it does the following:
- Replaces Bug followed by bug number with the generated link

What is still to be done:
- Replace 'Bug' followed by it's number with the following format [Bug 1234](https://bugzilla.mozilla.org/show_bug.cgi?id=1234) to make it markdown ready
- Debug `replace_bug_with_url` as it seems it fails in certain situations, not sure why
