### ISSUE TITLE
Main markdown table improvements

### ISSUE THREAD

**Issue by zsoltfay** [mozilla-releng/firefox-infra-changelog#177]
## Main markdown consistency
In case we have no commits affecting infra in the last 24h:
 - some repositories show "No push in the last day."
 - other repositores show nothing
We should have consistency and make all of them display the same messages.

## Small improvement
If no commits in the last 24h follow up the above mentioned message with: "see history of all commits here" linking this to the appropriate MD file

**Comment by raduiman** [comment]
This issue is fixed by PR #180 . I'll close it since the main_markdown_table is generated as expected.
-if no commits in the last 24h the following message is displayed for each repository "see history of all commits here" and is linked to the appropriate MD file
