### ISSUE TITLE
Generate MD file for every repository

### ISSUE THREAD

**Issue by zsoltfay** [mozilla-releng/firefox-infra-changelog#178]
Some repositories have json files but no MD files. We should have both a json and a MD file for every repository that we track, even if it's going to be empty.

**Comment by raduiman** [comment]
The MD file is missing for addonscript, balrogscript, pushsnapscript, signingscript and treescript. I'll try to fix this.

**Comment by raduiman** [comment]
- implemented in this commit: https://github.com/mozilla-releng/firefox-infra-changelog/pull/182/commits/f84e10f009c33c2834fce4089bfbdfc5264f756a

**Comment by raduiman** [comment]
MD files are generated for every repository that we track.
