### ISSUE TITLE
Divide client.py into separate files for git & hg

### ISSUE THREAD

**Issue by zsoltfay** [mozilla-releng/firefox-infra-changelog#190]
We want to have separate files to handle the git and hg parts respectively.

**Comment by mutterroland** [comment]
I'm currently working on this. Progress can be tracked on my branch ( https://github.com/mozilla-releng/firefox-infra-changelog/tree/rmutter).

**Comment by mutterroland** [comment]
#201

**Comment by mutterroland** [comment]
As #203 got merged, we can safely use the script separated into different files. What still has to be done here is #194

**Comment by mutterroland** [comment]
Implement logging in #206
