### ISSUE TITLE
Use of requests and urlopen

### ISSUE THREAD

**Issue by Akhliskun** [mozilla-releng/firefox-infra-changelog#191]
Currently we are using 2 different modules that can do the same thing:

- from urllib.request import urlopen = Used **once** in generate_hg_pushes_link()
- import requests = Used **twice** in get_version_from_build_puppet(), filter_hg_commit_data()

My recommendation is to use only one.

**Comment by tomprince** [comment]
I'd generally suggest preferring `requests` over the stdlib module.

**Comment by Akhliskun** [comment]
This was fixed in #247
