### ISSUE TITLE
All .json data should be saved in changelog.json

### ISSUE THREAD

**Issue by Akhliskun** [mozilla-releng/firefox-infra-changelog#193]
Currently each repository (Git and HG) have separated .json files that contain the changes that we save. 

For ease of use, we should also save the same data in a central location, eg changelog.json. If a developer wants quick access to all history, it will be easier to load one file vs a few dozen files.

**Comment by zsoltfay** [comment]
Current implementation idea is as follows:
- use the existing `json_writer` functions
- in addition to writing to the current json files, also write to `changelog.json`
- repository name will be the key and `new_commits` will be the sub-key(s) and value(s)
- the `changelog.json` will not contain `key[0]`

**Comment by mutterroland** [comment]
This has been implemented so I'm going to close this issue for now.
