### ISSUE TITLE
Use "%s" in logger.

### ISSUE THREAD

**Issue by bccrisan** [mozilla-releng/firefox-infra-changelog#209]
Using code like:
``` Python
LOGGER.info('========Logging for {} on {} ========'.format(str(new_list).strip('[]'), datetime.now()))
```
It is not correct. The correct versions should look like:
``` Python
LOGGER.info('========Logging for %s on %s ========',str(new_list).strip('[]'), str(datetime.now())))
```
```
W1202: Use % formatting in logging functions and pass the % parameters as arguments (logging-format-interpolation)
```

The benefit of using this is that the string will be interpolated only when 2nd string is produced/exists.

**Comment by Akhliskun** [comment]
I can't seem to find any other places where this is not using the recommended formatting.
Closing the issue for now.
