### ISSUE TITLE
[click] Argument -d removed without documentation.

### ISSUE THREAD

**Issue by Akhliskun** [mozilla-releng/firefox-infra-changelog#221]
In PR #201 we have removed the old argument --d.
I know this was a WIP that was merged by @bccrisan but what I'm wondering if the removal of --d was intentional or not, as I can't find any documented explanation that it was been removed intentionally. 

As per our new workflow, if this was been removed by mistake, we need to re-add it as all other functions are still in the code (just the arg handler missing).

Please also re-adding it following the new requirements for how we use agruments, eg `-d` and `--days`

**Comment by bccrisan** [comment]
I don't know if it unintended. I know that at the time when we started using the click library we had issues with -d and -l arguments. 
I'm not 100% about that also.

**Comment by mutterroland** [comment]
This has been handled in #243
