### ISSUE TITLE
Changelog.json is being re-written too many times

### ISSUE THREAD

**Issue by zsoltfay** [mozilla-releng/firefox-infra-changelog#222]
Currently changelog.json is being re-written every time any repository has new infra-affecting commits. This is an I/O optimization issue as the file will reach large size.
 
We would like to have a function that populates changelog.json with the data found in every json file from "git_files" and "hg_files", AFTER the filtering functions have finished their work.

```python
# What we currently do.
with open("secret_data.txt", "a") as file:
    for i in range(1, 101):
        file.write(str(i) + "\n")  # Write to the file each iteration


# What we need to do:
data_to_write = ""  # Allocate space in memory

for i in range(1, 101):
    temp_var = data_to_write
    data_to_write = temp_var + str(i) + "\n"  # Populate data to memory

with open("secret_data.txt", "a") as file:
    file.write(data_to_write)  # Write to file ONLY once
```

**Comment by bccrisan** [comment]
Probably a dictionary that gets populated opening each JSON file one by one and at the end, write the dictionary content as JSON with dump and index=2
