### ISSUE TITLE
Clean and tidy code

### ISSUE THREAD

**Issue by zsoltfay** [mozilla-releng/firefox-infra-changelog#25]
## Noteworthy:
Keeping the code clean and well document. This will allow us to easier read and understand the code, but also will help any new or returning people who are going to work on this to better understand what has been done thus far.

## Good Practice:
I'm suggesting to attach this issue to the milestone with the closest deadline so we always do a tidiness-check before each deadline.

**Comment by bccrisan** [comment]
Here is my list of checks that I do before pushing the code in my dev branch:
- Check all of the IDE highlights/issues/red-flags and resolve them
- Document the code (function python description (those triple quotes one) as well as blocks of code in case where chunks of code can't be divided/splitted)
- check for unused variables and imports
- make sure that you import only the module not the whole library, where it's possible
- make sure that you have written code that it is optimized for memory usage (to get the size of an object you can use `print(sys.getsizeof(object_with_unknown_size))` )
- optimize the code for speed, multiple versions can be used here - [examples](https://stackoverflow.com/questions/7370801/measure-time-elapsed-in-python)
- Use list comprehension/dictionary comprehension
- Check the branch you are pushing into, if you worked on a wrong branch ([use gith stash](https://git-scm.com/docs/git-stash))

[Interesting medium article](https://medium.freecodecamp.org/an-a-z-of-useful-python-tricks-b467524ee747)
That's pretty much how I do things, if any of you have any other recommendations please leave a comment 👍

**Comment by Akhliskun** [comment]
Finally, we can close this 🎉 
Good job everyone!
