### ISSUE TITLE
[GIT] Handle GitHub server errors

### ISSUE THREAD

**Issue by Akhliskun** [mozilla-releng/firefox-infra-changelog#267]
Whenever we work with GitHub, we need to make sure that we handle server response codes.
Currently we are not doing this, so if GitHub is down or under heavy load, the script will crash with something like this:

```(e.g raise self.__createException(status, responseHeaders, output)
    github.GithubException.GithubException: 502 {'message': 'Server Error'}
```
## Here is a checklist of response codes that we need to handle:
- [ ] 301 
- [ ] 302
- [ ] 304
- [ ] 307
- [ ] 400
- [ ] 401
- [ ] 403
- [ ] 404
- [ ] 422
- [ ] 500
- [ ] 501
- [ ] 503

**Comment by zsoltfay** [comment]
After some research I've found a way to make this possible if we include the cli() function into a try-except block such as:

```Python
try:
    cli()
except GithubException as placeholder_var:
    if placeholder_var.status == 301:
        handle_it()    
```
