### ISSUE TITLE
[Weekly Release] 03-08-2019

### ISSUE THREAD

**Issue by bccrisan** [mozilla-releng/firefox-infra-changelog#286]
**Date**: 03-08-2019

**Reviewer**: Bogdan Crisan ([bccrisan](https://github.com/bccrisan))
## Known Issues:
- [GIT] Handle Github server errors #267 

## Status:
- [x] Script is running on normal mode (-c)
- [x] Script is running on verbose mode (-c -l)
- [x] Script is running only for Github repositories (-g)
- [x] Script is running only for Mercurial repositories (-hg)
- [x] Script is running on manual mode (-m build-puppet)

## Changelog:
- Issue #238 - Handle script interruptions in the middle of action #271
- Issue #205/ #245 - Update DocStrings. #265
- Issue #262 Implement Logger Level based on Environment variable. #263
- Remove LOG.log from git add as it is ignored #260
- Improve auto-push.py #259
- Fix issue with PR252 #258
- Issue #166: Generate and add Bugzilla links to the bug numbers in markdown files. #252
- Issue #219: Fix the Mercurial logic to show commits in the markdown table from the newest to oldest #251
- Issue #236: Handle unknown arguments #248
- Issue #191: Only use requests to grab url data #247
- Issue #235: Replace print with LOGGER in limit_checker() #244
- Issue #221: Reimplemented -d argument #243
- Issue #241: Update README.md #242
- Issue #239: Fix problems with click arg rename #240
- Added missing module docstring by moving the existing docstring #234
- Renamed 'all' to 'complete', issue #228 #233 
- Moved code to functions, fix for issue #227 #232 
- Fixed import order by moving click in the right place #231 
- Fixed issue 225 by adding a default case for the arguments #230 
- Reconfigured scriptworker repositories #224

**Comment by bccrisan** [comment]
For the next release we need to update the wiki and add 3 test cases.
- Script is running only for Github repositories with logging (-g -l)
- Script is running only for Mercurial repositories with logging (-hg -l)
- Script is running on manual mode with logging (-m -l) (and select a repo and multiple repositories to test it)

**Comment by Akhliskun** [comment]
Thank you for the work!
I have implemented the requested changes in the Wiki page.

Release Draft status has been changed to published 🍺 🍻
