### ISSUE TITLE
[Changelog.json] Move code that updates changelog.json to a function and document it.

### ISSUE THREAD

**Issue by bccrisan** [mozilla-releng/firefox-infra-changelog#303]
While investigated issue 295 and 296 I have found a very important block of code that should not be left without documentation and without the attention it needs.

```Python
    data_file = open("changelog.json", "w")
    json.dump(git_data, data_file, indent=2)
    json.dump(hg_data, data_file, indent=2)
    data_file.close()
```
This should be a function that should have a title like `update_changelog_json()` and it could handle cases when just the git or hg data have been generated.

```Python
def update_changelog_json(json_data):
    data_file = open("changelog.json", "w")
    json.dump(json_data, data_file, indent=2)
    data_file.close()
```
and, as expected, the code doesn't properly update the `changelog.json`.
Dumping data to a file, without respecting the JSON format leads to errors like "end of file expected"

We should:
 - Read data from file
 - Update the data with new values
 - Write data back to `changelog.json`

**Comment by bccrisan** [comment]
One way we can resolve this would be creating a JSON root that has as keys each repository name and dumps the content from the JSON files as values.

**Comment by zsoltfay** [comment]
### Created branch issue-303 and started working on improving the way "changelog.json" is being populated.

- When the script is ran in -c mode all the git and hg data (stored in "git_data", and "hg_data") is now added to a main dict called "changelog_data". 
- This is then dumped to "changelog.json" so we only have one main object, thus avoiding the "end of file expected" error in the middle of the file.

### Wrote a function called "write_to_changelog_json". This is used for when the script is ran in Git or Hg mode.
 
Changes are still only on branch issue-303. Feel free to test it more. 

**TO-FIX**: The script will fail if the first run on a **fresh clone** is not done in "-c" mode.
