### ISSUE TITLE
Update the 'folders-to-check' list for mozilla-beta 

### ISSUE THREAD

**Issue by raduiman** [mozilla-releng/firefox-infra-changelog#328]
Currently the list of the tracked files for mozilla-beta contains:
   "folders-to-check": ["testing/mozharness", "taskcluster"]

We have to add other folders that affect infra to this list.

During my shift, @lundjordan reported a missing commit from changelog. 
https://hg.mozilla.org/releases/mozilla-beta/rev/a0881eefea64#l1.13

After a close look, I noticed that the file modified by this commit is not in the 'folders-to-check' list from mozilla-beta.

Here are the folders from [python](https://hg.mozilla.org/releases/mozilla-beta/file/tip/python). Which of these folders affect the infra? @lundjordan should we add the entire folder?

**Comment by lundjordan** [comment]
Thanks Radu!

Lets start with python/mach and python/mozrelease
