### ISSUE TITLE
Fix issues already merged into master from Pull28

### ISSUE THREAD

**Issue by danlabici** [mozilla-releng/firefox-infra-changelog#36]
As PullRequest #28 was already merged, and it has a few issues, we will need to come back to this and fix all the issues listed in the PR.

Please push the fixed in a stand alone PR, without other content, just the fixes.

**Comment by bccrisan** [comment]
Fixed in https://github.com/Akhliskun/firefox-infra-changelog/commit/5132f248878f9e830492008cd63d62bb8e28de56
