### ISSUE TITLE
[Github] Make PRs after autopush.

### ISSUE THREAD

**Issue by Akhliskun** [mozilla-releng/firefox-infra-changelog#367]
## This issue can't be done until Issue #366 is completed!

Once a day, we will need the tool to automatically make a PR from auto-push branch and merge it to master. 
I'm not sure here we should start, so if you guys have any ideas please share them here.

**Comment by bccrisan** [comment]
One way will be avoiding the merge.
There is a setting in the git repository that let's you choose the default branch, so choosing the `auto-push` branch as default will always show the updated files when opening the github project page.
Another option will be pushing directly to master branch, again, just to hesitate the need of merge.

Probably the best solution will be pushing to auto-push and doing the merge locally. We can resolve the merge conflicts (if any) by accepting all of the changes from the auto-push branch..

**Comment by Akhliskun** [comment]
This will be closed as we gonna push to master right away.
