### ISSUE TITLE
Update requierments.txt with all of the used packages.

### ISSUE THREAD

**Issue by bccrisan** [mozilla-releng/firefox-infra-changelog#385]
Please make a list of used python packages and update the `requierments.txt`
At the moment we only have a few packages in requierments.txt. 
Those requierments.txt should also be used later when we need to do the configuration on buildduty tools.

**Comment by mutterroland** [comment]
For now we have the following packages in our requierments.txt:
```
pygithub>=1.43.5
py-dateutil>=2.2
click>=7.0
requests>=2.21.0
```
Had a look over the imports and it seems like the remaining packages that we are using are currently included in The Python 3 Standard Library (https://docs.python.org/3/library/)

**Comment by raduiman** [comment]
Fixed in:
https://github.com/mozilla-releng/firefox-infra-changelog/commit/402bed6edf05f458f944ffbf3fdeb1369eab94b1
https://github.com/mozilla-releng/firefox-infra-changelog/commit/54fa0fa5df588bf7646301ee66e772f776170012

**Comment by bccrisan** [comment]
After doing a small investigation, I have created a virtualenv in which I have installed all the dependencies and used `pip freeze` to show the installed packages.
Here is a list of packages that would need to be added to the repository.
```
λ pip freeze
asn1crypto==0.24.0
certifi==2019.3.9
cffi==1.12.2
chardet==3.0.4
Click==7.0
cryptography==2.6.1
Deprecated==1.2.5
gitdb2==2.0.5
github3.py==1.3.0
GitPython==2.1.11
idna==2.8
jwcrypto==0.6.0
py-dateutil==2.2
pycparser==2.19
PyGithub==1.43.6
PyJWT==1.7.1
python-dateutil==2.8.0
requests==2.21.0
six==1.12.0
smmap2==2.0.5
uritemplate==3.0.0
urllib3==1.24.1
wrapt==1.11.1
```
The above actions have been done following this [guide](https://wiki.mozilla.org/ReleaseEngineering/How_To/Install_a_Python_Virtualenv_with_Puppet).
