### ISSUE TITLE
Integrate update-files.py into client.py

### ISSUE THREAD

**Issue by bccrisan** [mozilla-releng/firefox-infra-changelog#402]
ATM we have a separated file that we call when we want to do a manual update.
As we talked in the workweek, we have decided that the OOP implementation of the application to include this part of the file as a method/function in the script and call it from there when we want to manually update the files.
It should be done using command line arguments.

#### Content of the file:
```Python
from fic_modules.GITMethods import FICGithub
import subprocess
from fic_modules.configuration import LOGGER
from datetime import datetime

config = "."
commit_message = "Changelog: " + str(datetime.utcnow())
files = ["git_files", "hg_files", "changelog.json", "changelog.md"]

update_fic_files = FICGithub(files, commit_message, LOGGER, config)

update_fic_files.git_pull()
subprocess.call(['python', 'client.py', '-c', '-l'])
update_fic_files.git_add()
update_fic_files.git_commit()
update_fic_files.git_push()
```

**Comment by Akhliskun** [comment]
Added `priority: Low` as this will be "passively" added as we progress on the logic.
The only real step that we have to do it delete the file.
