### ISSUE TITLE
Store git_files and hg_files to a separated folder

### ISSUE THREAD

**Issue by bccrisan** [mozilla-releng/firefox-infra-changelog#404]
We used to save the JSON/MD data as files under `hg_files` and `git_files` folders (separated).
In the OOP world, we will use a folder called `data` to store all of the generated files.
All of the `.json` and `.md` files will be stored under `data` folder.

**Comment by Akhliskun** [comment]
Edited the issue description as we later (after we took note of this issue) to simply name the folder `data` and not `changelog_data`
