### ISSUE TITLE
Rename command line arguments as discussed in the workweek.

### ISSUE THREAD

**Issue by bccrisan** [mozilla-releng/firefox-infra-changelog#406]
As discussed in the workweek, the new implementation of the scrip should include the rename of the follwing CLI arguments along with the proper short version for them:
 - Rename `--manual` to `--repo`
 - Rename `--complete` to `-all`
 - Rename `--update` to `--push`

### [OLD] The current flags are:
| Short Flag | Long Flag | Description |
|-----|-----|----------------------------------------------------------------------------|
| -c | --complete  | Runs script for all available repositories
| -g | --git  | Runs script only for repos that are on GitHub                              |
| -hg | --mercurial   | Runs script only for repos that are on Mercurial                           |
| -m | --manual    | Let the user choose for which repositories the script will run             |
| -l | --logger    | Activate logger output in the console             |
| -d | --days | Generate the **changelog.md** for `<int>` amount of days. |
| -u | --update | Runs script for all available repositories and auto push the changes to github. |

### [NEW] Proposed flags:
| Short Flag | Long Flag | Description |
|-----|-----|----------------------------------------------------------------------------|
| -a | --all | Runs script for all available repositories
| -g | --git  | Runs script only for repos that are on GitHub                              |
| -hg | --mercurial   | Runs script only for repos that are on Mercurial                           |
| -r | --repo | Let the user choose for which repositories the script will run             |
| -l | --logger    | Activate logger output in the console             |
| -d | --days | Generate the **changelog.md** for `<int>` amount of days. |
| -p | --push | Runs script for all available repositories and auto push the changes to github. |

**Comment by Akhliskun** [comment]
Work on this issue was started during the workweek and progress can be seen here: [FIC_Mainmenu](https://github.com/mozilla-releng/firefox-infra-changelog/blob/oop/modules/FIC_MainMenu.py#L18)
