### ISSUE TITLE
Rename NUMBER_OF_CHANGESETS to something more verbose

### ISSUE THREAD

**Issue by bccrisan** [mozilla-releng/firefox-infra-changelog#408]
In configuration.py we have:
```Python
NUMBER_OF_CHANGESETS = int(100)
```
we should rename it to something more verbose.
In the new OOP implementation we have
```Python
HG_CHANGESETS_TO_SHOW = int(100)
```
is it the same thing? should we have similar to git?
or rename it to `CHANGES_TO_SHOW`??

**Comment by Akhliskun** [comment]
This rename was been done during the workweek and the request is completed.
The old `NUMBER_OF_CHANGESETS` was only used by `hg` when generating the URL link used to pull data about a repo, it wasn't used in git at all.
