### ISSUE TITLE
Define a list of files that affects our infrastructure

### ISSUE THREAD

**Issue by bccrisan** [mozilla-releng/firefox-infra-changelog#41]
Now that we have the list of repositories we should start by asking each of the developers/contributors (that maintain these repositories) which files/folders (if that's the case) affects our infrastructure and how bad in case of an issue.

As discussed in the meeting from November 5'th, 2018 we should start asking every shift with the contributors.

#### GitHub repositories:
* Ship it - https://github.com/mozilla-releng/ship-it
* services - https://github.com/mozilla/release-services
* beetmoverscript - https://github.com/mozilla-releng/beetmoverscript
* addonscript - https://github.com/mozilla-releng/addonscript
* ship it V2 - https://github.com/mozilla-releng/shipit-v2
* build-cloud-tools - https://github.com/mozilla-releng/build-cloud-tools
* build-puppet - https://github.com/mozilla-releng/build-puppet
* shipitscript - https://github.com/mozilla-releng/shipitscript
* bouncerscript - https://github.com/mozilla-releng/bouncerscript
* treescript - https://github.com/mozilla-releng/treescript
* mozapkpublisher - https://github.com/mozilla-releng/mozapkpublisher
* OpenCloudConfig - https://github.com/mozilla-releng/OpenCloudConfig
* scriptworker - https://github.com/mozilla-releng/scriptworker
* pushsnapscript - https://github.com/mozilla-releng/pushsnapscript
* signingscript - https://github.com/mozilla-releng/signingscript
* pushapkscript - https://github.com/mozilla-releng/pushapkscript
* balrogscript - https://github.com/mozilla-releng/balrogscript
* funsize - https://github.com/mozilla-releng/funsize
* signtool - https://github.com/mozilla-releng/signtool
* shipitapi - https://github.com/mozilla-releng/shipitapi
* ami-builder - https://github.com/mozilla-releng/ami-builder

#### HG repositories:

* Mozilla Build - https://hg.mozilla.org/mozilla-build/
* Mozilla Central - https://hg.mozilla.org/mozilla-central/
* Try - https://hg.mozilla.org/try/
* Autoland - https://hg.mozilla.org/integration/autoland/
* Inbound - https://hg.mozilla.org/integration/mozilla-inbound/
* comm-esr60 - https://hg.mozilla.org/releases/comm-esr60/
* Beta - https://hg.mozilla.org/releases/mozilla-beta/
* mozilla-esr60 - https://hg.mozilla.org/releases/mozilla-esr60/
* mozilla-release - https://hg.mozilla.org/releases/mozilla-release/
* braindump - https://hg.mozilla.org/build/braindump/
* CI Configuration - https://hg.mozilla.org/build/ci-configuration/
* CI Admin - https://hg.mozilla.org/build/ci-admin/

#### Ignored repositories:
* Version Control Tools - https://hg.mozilla.org/hgcustom/version-control-tools/
* mozharness - https://hg.mozilla.org/build/mozharness/
* cot-gpg-keys - https://github.com/mozilla-releng/cot-gpg-keys
* binary-transparency - https://github.com/mozilla-releng/binary-transparency
* pulse-notify - https://github.com/mozilla-releng/pulse-notify
* mozilla-version - https://github.com/mozilla-releng/mozilla-version

## Action Items
* Identify who are the contributors of the project
* Get in touch with them 
* Explain to them what we are trying to accomplish
* Take notes and make sure to update this issue
* Implement changes (that would mean updating the `repositories.json` file)

**Comment by lundjordan** [comment]
Great. Okay, so perhaps we should open a new github issue for each repo in this list.

Then go through the action items defined above, asking the core contributor of that project what files/dirs affect production **and also** how to tell what has actually been deployed. e.g. just because it is on master or pushed to some branch, does not mean it's live yet. We need to know how to tell what has been deployed in each repo.

**Comment by bccrisan** [comment]
The taskcluster's repositories mentioned above have been added to the `repositories.json` in commit https://github.com/Akhliskun/firefox-infra-changelog/commit/28a64fbdf4bf8a47b97e5efa3c9a1586b074ce94 that will probably be reviewed in the next shift and merged if all is good.
I also make sure that the script does not fail to create the md files for them and doesn't throw errors. All good on the first run \o/.

**Comment by bccrisan** [comment]
Added `Ignored repositories` category and moved "Version Control Tools, mozharness, binary-transparency, cot-gpg-keys, pulse-notify, mozilla-version" there. (In the first comment of this issue.)

Under HG, should we go with just one repository? or keep all of them and have gecko duplicates?

**Comment by lundjordan** [comment]
We can simplify and use one gecko based hg repo for now. e.g. mozilla-central. But going forward, we should keep in mind a way to quickly tell what's changed on a given repo. e.g. if treeherder reports bad infra for just mozilla-beta, we need a way to see what has changed to just mozilla-beta.

**Comment by lundjordan** [comment]
Taskcluster wise, pulse-go, taskcluster-cli, and taskcluster-retrospectives are probably safe to ignore as they don't sound like repos that would be used in prod infra. Perhaps others too

**Comment by bccrisan** [comment]
I think we can start with these and as we go, we can continue to add more repositories after that:
1. generic-worker	- A generic worker for TaskCluster, written in go
2. taskcluster-tools -  Tools for debugging, inspecting and managing Taskcluster
3. docker-worker - Docker based worker for TaskCluster
4. mozilla-taskcluster - Mozilla + Taskcluster handles integrations between mozilla components (hg/pushlog/treeherder) and taskcluster
5. taskcluster-builder - Tool for building Taskcluster releases
6. aws-provisioner - AWS Provisioner for Taskcluster

**Comment by zsoltfay** [comment]
We have a well established list of what files we need to track within each repo
