### ISSUE TITLE
Add ability to store data for a specific amount of time.

### ISSUE THREAD

**Issue by bccrisan** [mozilla-releng/firefox-infra-changelog#412]
At the moment, we store data for unlimited time.
Given the current limits, we need to limit the data we store.
The specified amount of time should be stored in configuration and should be defined in days(int) we want to retain it.

**Comment by zsoltfay** [comment]
Started working on this issue. The progress can be found on its respective branch.
I've implemented the git part. We should do the same for the code inside Mercurial.py

**Comment by zsoltfay** [comment]
This has been done in PR #480
