### ISSUE TITLE
[FileHandler] Add extra functionality to FileHandler

### ISSUE THREAD

**Issue by Akhliskun** [mozilla-releng/firefox-infra-changelog#420]
**Overview**
As we wish FileHandler to hold all the logic for when we need to implement a bunch of new functionality, when compared to the old FIC codebase, as listed below:

**Functionality**:
- [x]  Check that folders/files exist:
- - [x] data (folder)
- - [x] modules (folder)
- - [x]  - All module files `.py` <- If missing, download latest version from GitHub
- - [x] plugins (folder)
- [x] Check FileSize
- [x] Rename filename (used for keeping `.md` files under `1mb` 
- [x] Handle OS paths (Unix/NT)
- [x] **LOWPRIO** Check that you have rights to write to a file.
- [ ] **LOWPRIO** Ability to write to temp. files, if tool runs everything successfully move them to the proper locations.

**Comment by Akhliskun** [comment]
I have started to work on this Issue locally.
Will send parts of the code for reviews as mini-PRs.

**Comment by bccrisan** [comment]
For the check that we have the rights to write to a file I have created two new methods `is_readable()` and `is_writable()` and added them to the FileHandler in PR https://github.com/mozilla-releng/firefox-infra-changelog/pull/426

**Comment by bccrisan** [comment]
I was also thinking how we can approach the ability to write to temp files and if the tool runs everything successfully, move them to the proper locations.
That should be just a matter of renaming the files and the os library gives us `os.rename()` method.
I will implement it and add it to the current PR.

**Comment by Akhliskun** [comment]
Everything except the `write temp files` was been done, closing this Issue and the missing step, which is LOW Priority, can have its own dedicated issue.
