### ISSUE TITLE
Update repos

### ISSUE THREAD

**Issue by klibby** [mozilla-releng/firefox-infra-changelog#423]
In repositories/mercurial_repositories.md, at the bottom, you have a section of "maybe" repos. Those are no longer valid, or in use. The repo you DO want, however, is https://hg.mozilla.org/hgcustom/version-control-tools/ as it controls the configuration of hgmo.

And in github_repositories.md, you should add the following:

- https://github.com/mozilla-platform-ops/relops-image-builder 
- https://github.com/mozilla-platform-ops/relops-hardware-controller
- https://github.com/mozilla-platform-ops/ronin_puppet (WIP, will eventually replace build-puppet)

**Comment by Akhliskun** [comment]
@klibby Thanks for pointing it out the missing repos.

@mutterroland Please add the listed repositories and give them an order value above script workers, as we don't know how important they are *yet*, and land the code in master (no review needed).
All you should do is, add them in [repositories.json](https://github.com/mozilla-releng/firefox-infra-changelog/blob/master/repositories.json) and make sure that the files exist in hg/git data folders.

Once that's done, don't forget to use update-files.py to push the new repos to github changelog.md

**Comment by klibby** [comment]
(carrying the conversation from slack back to the PR so that it's easier to track)

Interesting files/folders within the above repos...  

In version-control-tools there's quite a lot, probably enough to look at it as what to exclude. I think all of the top level files can be ignored, and then ignore the following directories: vcssync, third_party, testing, docs, and git. Pretty sure the rest all contain something that could break CI.

In relops-image-builder, just about everything except the license, readme, and gitignore.

In relops-hardware-controller, gonna say that most of the top level files, plus the relops_hardware_controller directory. 

In ronin_puppet, pretty much everything except the obvious top level files (readmes, etc).

**Comment by mutterroland** [comment]
I've finished including the requested repos into the script. As I merged #424 , I'm going to close this issue.
