### ISSUE TITLE
Construct the data to be writen into json files

### ISSUE THREAD

**Issue by zsoltfay** [mozilla-releng/firefox-infra-changelog#449]
## What do we have right now:
At the moment we are only saving the new commits into the json files.

## What we miss:
* **FOR GIT** the first element containing last_checked and version (if necessary)  
* **FOR HG** the first element containing last_push_id
* the old/local commits

## Solution
have a dedicated dictionary that we build:
* we add the proper first element
* update it with the new commits
* add the local commits
* ```json.dump``` this dictionary into the proper json file

**Comment by zsoltfay** [comment]
# The first additions to branch issue-449: 

## _local_version() method was unused - commit link 0c405057aa14bdc31a6f8691acc7568a10978cef:
this method was never called thus ``` self.local_version``` would always be **None**

## Changed _get-release() to be more universal - commit 86704202c9a3397bcadf2e48690362b42c6933b4:
* previously this method was storing the version of the latest release as such:
```python
def _get_release(self):
    self.release_version = [tag for tag in self.repo_data.tags(number=1)][0].name
```
* This commit changes the method to return a release version of our choosing by accepting an integer argument. If the argument is "1" it will return the latest version, "2" will return the second to latest version, and so on
* When the json files are missing, we would create them with _create_missing_repo_files() and write the first element into them. The problem was in this line, as ```self.local_version``` would be None since there would be no previous file to extract it from:
```python
return {"0": {"last_checked": return_time("%Y-%m-%dT%H:%M:%S.%f", "sub", 2), "version": self.local_version}}
```
* Now the first element will contain the second latest version, thus allowing us to save all the commits up to the latest tag which are not older than a month when ```start_github()``` is called  

By using _addonscript_ as the testing repository the results were as expected:
This test code:
```python
a = FICGithub()
a.repo_name = "addonscript"
a._repo_team()
a.read_repo()
a.repo_type = "tag"
a.release_version = a._get_release(1)
print("first element: ", a._generate_first_element_git(a.repo_type))
print("last official release: ", a.release_version)
```
Returned the expected versions:
```
first element:  {'0': {'last_checked': '2019-05-09T03:02:57.750501', 'version': '0.4'}}
last official release:  1.0

Process finished with exit code 0
```

**Comment by mutterroland** [comment]
#453 <- Hg part of this issue

**Comment by raduiman** [comment]
The HG part was implemented in PR: https://github.com/mozilla-releng/firefox-infra-changelog/pull/459
