### ISSUE TITLE
[Git-oop] Multiple returns missing in FIC_Github.py

### ISSUE THREAD

**Issue by mutterroland** [mozilla-releng/firefox-infra-changelog#450]
Looks like every method that saves information in variables is missing the return. I'm not sure if the return is mandatory, but, looking into FIC_Mercurial.py the return may or may not be mandatory. Will make a patch for that and I'm waiting for your opinions as well.

**Comment by mutterroland** [comment]
https://github.com/mozilla-releng/firefox-infra-changelog/commit/0362dec0c549cb63df1d2d95d0aa2da4d3497787

**Comment by bccrisan** [comment]
Merged and can be closed for now.
