### ISSUE TITLE
[MainMenu] Code improvements

### ISSUE THREAD

**Issue by Akhliskun** [mozilla-releng/firefox-infra-changelog#457]
Currently the MainMenu module is using some outdate code and we need to re-write parts of it.

Specifically we need to use `self.load`, `self.constract_path`, etc.
We need to re-arange the functions a bit to follow a more "organic" flow in the file.
We also don't need `construct_repository_list` and `_load_repository_data` in their current form.

And most importantly:

-  we need to convert the repo selection menu to accept a list of repos (eg: 10, 20, 15, etc) instead of one at a time.

- we also want the repo selection menu to construct a list of tuples (repo-name, repo-type) to make things easier when we need to access the data inside `FIC_Core.py`

**Comment by Akhliskun** [comment]
I'm gonna work on this during my next business hours.

**Comment by raduiman** [comment]
@Akhliskun has implemented all these improvements in PR #467 
Thanks o/
