### ISSUE TITLE
[Mercurial] Code Improvements

### ISSUE THREAD

**Issue by zsoltfay** [mozilla-releng/firefox-infra-changelog#461]
At the moment `_construct_json_dict(self)`  is large and complex. It should be split up into smaller methods which are easier to read and understand. Each small method could perform one task as described:
* prepare the `final_dict` dictionary to accept data
* get the local json data(if any)
* iterate through the new changesets and retrieve their data
* iterate through the commits of each changesets and save wanted data

**Comment by bccrisan** [comment]
Implemented and code has been merged.
Please reopen if it's something else needed to do.
