### ISSUE TITLE
[Markdown] Handle MD tables when no data to be shown

### ISSUE THREAD

**Issue by zsoltfay** [mozilla-releng/firefox-infra-changelog#466]
The markdown logic is nearly complete, however there is one **major** issue that still needs to be dealt with. 

If for a specific repo there is no data for the past "X" days, we should have a method in place that will make sure something is displayed. E.G.:
`No push in the last 3 days.. see the history of MD commits` 

Part of the text should link to a more data-complete file

### The method needs to be adjusted for 3 different scenarios:
* individual git MD files
* indifivual hg MD files
* changelog.md when there is no data to show for a given repo

**Comment by raduiman** [comment]
I've implemented the fix for the individual git and hg MD files in PR #468 
Regarding changelog.md:
 - the current implementation will add only the repositories with changes in the last amount of days set by user or DEFAULT_DAYS. The repositories with no changes during this period of time will not be added to the MD table.

**Comment by raduiman** [comment]
In order to add each repository, whether or not has changes, we have to rewrite 'def create_changelog_md(self):' method.

**Comment by zsoltfay** [comment]
Added a few changes to avoid rewriting `def create_changelog_md(self)` method:

### Changed `no_data_for_md` method:
* renamed `repository_type` to `argument`. Why? So both the **IF** and the **ELIF** statement can make use of it
* replaced `self._get_js_md_links(self.repo_name)[1]` with `argument`. Why? The value that was being returned was already stored in `md_link`, thus there was no reason to run the method again. 
* changed the formatting of the **returned string** to accommodate these new changes

### Changed `_populate_changelog_md`:
- added an **IF/ELSE** statement to deal with the situations when there is no data to be written, by using the above mentioned method. The result is as such: 

![img](https://user-images.githubusercontent.com/37000130/58679653-28299b00-836d-11e9-96fc-6000c28ab4f3.PNG)

**Comment by raduiman** [comment]
Implemented in PR #468 and PR #473.
