### ISSUE TITLE
[Changelog.json] Reduce the size of files_changed.

### ISSUE THREAD

**Issue by mutterroland** [mozilla-releng/firefox-infra-changelog#472]
As we stand right now, the size of changelog.json is heavily influenced by the huge list of files_changed for different type of commits. To reduce the size of changelog.json we would like to find a way to target those specific commits and replace the list of files_changed with something like This commit contains X number of changed files . Refer to *LINK PLACEHOLDER* for full details.

**Comment by Akhliskun** [comment]
This suggestion came from Fubar after today's 1x1
