### ISSUE TITLE
Document all of the modules/functions and update README.md

### ISSUE THREAD

**Issue by zsoltfay** [mozilla-releng/firefox-infra-changelog#481]
As the project is nearly completed, we should document all the classes and methods that were used

**Comment by zsoltfay** [comment]
Added docstrings to github.py and markdown.py
The work can be found in 9b8c1a5 and c59dfaf on branch issue-481

**Comment by mutterroland** [comment]
Added docstrings to FIC_Mercurial.py in 7ae9641 .

**Comment by raduiman** [comment]
Added docstrings to FIC_Logger.py - https://github.com/mozilla-releng/firefox-infra-changelog/commit/d13b5df4736707f580cb821558e4243e57464db3 and FIC_Exceptions.py - https://github.com/mozilla-releng/firefox-infra-changelog/commit/59cf4f7659d5de2598f138eaf0beacd18d0596ed

**Comment by raduiman** [comment]
Added docstrings to FIC_Core.py - d6bb1b1f3becc2d7612059924ae0172cc05d3588

**Comment by bccrisan** [comment]
Added documentation to:
 - https://github.com/mozilla-releng/firefox-infra-changelog/commit/d308233523a03b86c219ca6d4807107a840eb66a
- https://github.com/mozilla-releng/firefox-infra-changelog/commit/13af09d48c1ef0d8151a900d898ae5d6099cd5ec
 - https://github.com/mozilla-releng/firefox-infra-changelog/commit/1ba8f41958315c8ebc726906f982075fedac2ef6
 - https://github.com/mozilla-releng/firefox-infra-changelog/commit/8037807f51781ca5e341bf18a47d83667aed5eaf
 - https://github.com/mozilla-releng/firefox-infra-changelog/commit/53d3af3d101d05ee25376ab5cdc1ce8a3985002e
 - https://github.com/mozilla-releng/firefox-infra-changelog/commit/5cf8ff27fc40b46dc146758e61496eb652e14422
- https://github.com/mozilla-releng/firefox-infra-changelog/commit/1009b033a4802ee77e9cca59d4c85c37068df9ef
 - https://github.com/mozilla-releng/firefox-infra-changelog/commit/708c5dbecb05e988612cba8d7da8c2236a968800
- https://github.com/mozilla-releng/firefox-infra-changelog/commit/58ee42fbe1a863aeec1786da8b8b514b1d0b1e40
- https://github.com/mozilla-releng/firefox-infra-changelog/commit/42ee095e9ed03ba860faa1faee353748ac511106
 - https://github.com/mozilla-releng/firefox-infra-changelog/commit/fb2c436eb4dfcf9bbae6ebf83984217daf49b853
- https://github.com/mozilla-releng/firefox-infra-changelog/commit/d385a82ca301f43b3cbd8a8c38e34a87a2d30cd2

**Comment by raduiman** [comment]
Added docstrings to FIC_MainMenu.py - https://github.com/mozilla-releng/firefox-infra-changelog/commit/9a8c18b6629ccd9e5cd8cb8d0c5aa2a3539fd26e

**Comment by Akhliskun** [comment]
Missing documentation, as of 20 June:

- [ ] extract_reviewer  - plugins/FIC_Markdown.py
- [ ] 
- [ ]

**Comment by raduiman** [comment]
Added docstrings for these methods in PR https://github.com/mozilla-releng/firefox-infra-changelog/pull/489

**Comment by zsoltfay** [comment]
Closing this as the code has been fully documented
