### ISSUE TITLE
Markdown Changelog

### ISSUE THREAD

**Issue by Akhliskun** [mozilla-releng/firefox-infra-changelog#5]
Using [tests/md_changelog.py](https://github.com/Akhliskun/firefox-infra-changelog/blob/master/tests/md_changelog.py) create a **test script** that will read the data stored in the following two json files: `git_changelog.json` , `hg_changelog.json` and add the aggregated and formatted data to `changelog.md`

## How data should be formatted:
# Github
| Time | SHA | Commit Msg | Committed by | Repository | Product | Component |
| --- | --- | --- | --- | --- | --- | --- |
| 07/13/2018 - 20:30 | 86fbbd2df71d | Danut Labici | The best commit that fixes all bugs | [Release Warrior](https://github.com/mozilla-releng/releasewarrior-2.0) | Desktop | Cloud-Tools |
| 07/13/2018 - 20:30 | 86fbbd2df71d | Danut Labici | The best commit that fixes all bugs | [Build Puppet](https://github.com/mozilla-releng/build-puppet) | Desktop | Cloud-Tools |
| 07/13/2018 - 20:30 | 86fbbd2df71d | Danut Labici | The best commit that fixes all bugs | [OpenCloudConfig](https://github.com/mozilla-releng/OpenCloudConfig) | Desktop | Cloud-Tools |
| 07/13/2018 - 20:30 | 86fbbd2df71d | Danut Labici | The best commit that fixes all bugs | [BB Configs](https://github.com/mozilla-releng/build-buildbot-configs) | Desktop | Cloud-Tools |

# Mercurial
| Time | SHA | Commit Msg | Committed By| Tree | Product | Component |
| --- | --- | --- | --- | --- | --- | --- |
| 07/13/2018 - 20:30 | 86fbbd2df71d | Danut Labici | The best commit that fixes all bugs | Moz-Build | Desktop | Cloud-Tools |
| 07/13/2018 - 20:30 | 86fbbd2df71d | Danut Labici | The best commit that fixes all bugs | Moz-Build | Desktop | Cloud-Tools |
| 07/13/2018 - 20:30 | 86fbbd2df71d | Danut Labici | The best commit that fixes all bugs | Moz-Build | Desktop | Cloud-Tools |
| 07/13/2018 - 20:30 | 86fbbd2df71d | Danut Labici | The best commit that fixes all bugs | Moz-Build | Desktop | Cloud-Tools |

## Requirements
* Don't use classes
* Runs on Py3.X
* Document the code

**Comment by bccrisan** [comment]
Is this still applicable??
I don't know where to place this.

At the moment we have the main markdown table that contains the last commit from every repository and we will also have the MD files for each repository linked to the main markdown table.
How are we going to link this to the rest of the project? or we will have a separate file (this md file) available as a stand alone MD file.

**Comment by Akhliskun** [comment]
This was completed a while ago.
