### ISSUE TITLE
Ship-It (files that afect FF-infra)

### ISSUE THREAD

**Issue by raduiman** [mozilla-releng/firefox-infra-changelog#55]
Define a list of files from this Repository which affects our infrastructure. 

## Where to start:
Identify who are the contributors of the project
Get in touch with them ( Email, Irc, GitHub etc)
Explain to them what we are trying to accomplish
Take notes and make sure to update this issue

**Comment by popadrianc** [comment]
The core contributor seems to be (based on the number of commits):
sylvestre

**Comment by mutterroland** [comment]
Sent email and created the following Gspreedsheet: https://docs.google.com/spreadsheets/d/1kLavopiM2U26a1XHzPUeTimkXMUYGx35nvr78YGBkbg/edit#gid=0

**Comment by bccrisan** [comment]
Set to be retired soon (end of the year) - not worth adding files to follow.

**Comment by zsoltfay** [comment]
Every repository is now configured (CiDuty knows what to track that affects infra)
