### ISSUE TITLE
Pushapkscript - files affecting infra

### ISSUE THREAD

**Issue by zsoltfay** [mozilla-releng/firefox-infra-changelog#65]
Repo in question is: https://github.com/mozilla-releng/pushapkscript

## Where to start:
Identify who are the core contributors of this project and get in touch with them via e-mail, Irc or GitHub.
Define a list of files from this repository which affect production.
Learn how to identify what has actually been deployed.

**Comment by zsoltfay** [comment]
The core contributor seems to be (based on the number of commits):

- johanlorenzo

**Comment by mutterroland** [comment]
Sent email and created the following Gspreedsheet: https://docs.google.com/spreadsheets/d/1kLavopiM2U26a1XHzPUeTimkXMUYGx35nvr78YGBkbg/edit#gid=0

**Comment by zsoltfay** [comment]
Every repository is now configured (CiDuty knows what to track that affects infra)
