### ISSUE TITLE
Distinguish between automatic deployment and the rest

### ISSUE THREAD

**Issue by zsoltfay** [mozilla-releng/firefox-infra-changelog#80]
As Dustin suggested, we should distinguish between things that deploy automatically and things that are deployed via some separate action.
This would help avoid the confusion when looking for a particular change or when it took effect.

**Comment by Akhliskun** [comment]
@zsoltfay Is this done yet?

**Comment by zsoltfay** [comment]
All repos are configured and we don't have bots that automatically push commits in the repos that we track.
