### ISSUE TITLE
Add taskcluter repositories to repositories.json

### ISSUE THREAD

**Issue by zsoltfay** [mozilla-releng/firefox-infra-changelog#89]
Added two repos, which have the highest potential to cause bustage:
taskcluster-auth : https://github.com/taskcluster/taskcluster-auth
taskcluster-queue : https://github.com/taskcluster/taskcluster-queue

## To-do
Still to confirm if we should track all files/folders or not.

**Comment by zsoltfay** [comment]
As Dustin confirmed, we should care about everything within these repositories.

**Comment by Akhliskun** [comment]
This was completed by Zsolt.
