### ISSUE TITLE
Error : UnicodeEncodeError: 'charmap' codec can't encode character '\u0131' in position 2583: character maps to <undefined>, while running the script

### ISSUE THREAD

**Issue by popadrianc** [mozilla-releng/firefox-infra-changelog#92]
**Describe the bug**
While running the script the following error appears : 
`Traceback (most recent call last):
  File "C:/repo/firefox-infra-changelog/client.py", line 351, in <module>
    create_files_for_hg()
  File "C:/repo/firefox-infra-changelog/client.py", line 221, in create_files_for_hg
    create_hg_md_table(repository_name)
  File "C:/repo/firefox-infra-changelog/client.py", line 112, in create_hg_md_table
    md_file.write(value + "\n\n")
  File "C:\Users\adrian.pop\AppData\Local\Programs\Python\Python36-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0131' in position 2583: character maps to <undefined>`

**Comment by bccrisan** [comment]
The explanation for this issue is in the commit author that contained char \u0131 (Latin I without `) in it.
In PR #93 I added a temporary fix. We should have a dedicated function that should replace all chars like this.

**Comment by mutterroland** [comment]
Reopening this as the PR made bccrisan is temporary.

**Comment by bccrisan** [comment]
[Note to me] Check Staff meeting doc for this (26 11 2018)
