### ISSUE TITLE
Get only the commits for the repository versions that are in production

### ISSUE THREAD

**Issue by zsoltfay** [mozilla-releng/firefox-infra-changelog#97]
So far we were getting the commits for the latest version of each repo. We need to check which version of each repo is live and only get the latest commits for that version.

**Comment by zsoltfay** [comment]
So far we are extracting the version of each *_scriptworker from build-puppet. We need to compare this version to what is live and only get the commits for this tag.

**Comment by raduiman** [comment]
- created another function to extract the latest two version of each repository using .get_tags() function
- it return a dictionary with the following keys: version, sha, author, date, 
-added this at the top of the JSON files: https://github.com/Akhliskun/firefox-infra-changelog/pull/106/files#diff-59c28c65f587aa13ad4fc4356154ef4cR4
-PR #106 

For each repo that has release versions we can get only the commits from the latest one. 

repository_version['PreviousRelease']['Date'] > current commits in production <= repository_version['LatestRelease']['Date']

**Comment by zsoltfay** [comment]
Added a check which verifies if a version bump happened to any repo defined in build-puppet that we care about, and updates the appropriate json files with all the new commits that enter production.

**Comment by raduiman** [comment]
Here are the repositories with release tags:
* mozilla/release-services -> [services.json](https://github.com/Akhliskun/firefox-infra-changelog/blob/master/git_files/services.json) - [services.md](https://github.com/Akhliskun/firefox-infra-changelog/blob/master/git_files/services.md)
* mozilla-releng/beetmoverscript -> [beetmoverscript.json](https://github.com/Akhliskun/firefox-infra-changelog/blob/master/git_files/beetmoverscript.json) - [beetmoverscript.md](https://github.com/Akhliskun/firefox-infra-changelog/blob/master/git_files/beetmoverscript.md)
* mozilla-releng/addonscript -> [addonscript.json](https://github.com/Akhliskun/firefox-infra-changelog/blob/master/git_files/addonscript.json) - [addonscript.md](https://github.com/Akhliskun/firefox-infra-changelog/blob/master/git_files/addonscript.md)
* mozilla-releng/shipitscript -> [shipitscript.json](https://github.com/Akhliskun/firefox-infra-changelog/blob/master/git_files/shipitscript.json) - [shipitscript.md](https://github.com/Akhliskun/firefox-infra-changelog/blob/master/git_files/shipitscript.md)
* mozilla-releng/bouncerscript -> [bouncerscript.json](https://github.com/Akhliskun/firefox-infra-changelog/blob/master/git_files/bouncerscript.json) - [bouncerscript.md](https://github.com/Akhliskun/firefox-infra-changelog/blob/master/git_files/bouncerscript.md)
* mozilla-releng/treescript -> [treescript.json](https://github.com/Akhliskun/firefox-infra-changelog/blob/master/git_files/treescript.json) - [treescript.md](https://github.com/Akhliskun/firefox-infra-changelog/blob/master/git_files/treescript.md)
* mozilla-releng/mozapkpublisher -> [mozapkpublisher.json](https://github.com/Akhliskun/firefox-infra-changelog/blob/master/git_files/mozapkpublisher.json) - [mozapkpublisher.md](https://github.com/Akhliskun/firefox-infra-changelog/blob/master/git_files/mozapkpublisher.md)
* mozilla-releng/scriptworker -> [scriptworker.json](https://github.com/Akhliskun/firefox-infra-changelog/blob/master/git_files/scriptworker.json) - [scriptworker.md](https://github.com/Akhliskun/firefox-infra-changelog/blob/master/git_files/scriptworker.md)
* mozilla-releng/pushsnapscript -> [pushsnapscript.json](https://github.com/Akhliskun/firefox-infra-changelog/blob/master/git_files/pushsnapscript.json) - [pushsnapscript.md](https://github.com/Akhliskun/firefox-infra-changelog/blob/master/git_files/pushsnapscript.md)
* mozilla-releng/signingscript -> [signingscript.json](https://github.com/Akhliskun/firefox-infra-changelog/blob/master/git_files/signingscript.json) - [signingscript.md](https://github.com/Akhliskun/firefox-infra-changelog/blob/master/git_files/signingscript.md)
* mozilla-releng/pushapkscript -> [pushapkscript.json](https://github.com/Akhliskun/firefox-infra-changelog/blob/master/git_files/pushapkscript.json) - [pushapkscript.md](https://github.com/Akhliskun/firefox-infra-changelog/blob/master/git_files/pushapkscript.md)
* mozilla-releng/balrogscript -> [balrogscript.json](https://github.com/Akhliskun/firefox-infra-changelog/blob/master/git_files/balrogscript.json) - [balrogscript.md](https://github.com/Akhliskun/firefox-infra-changelog/blob/master/git_files/balrogscript.md)
* mozilla-releng/signtool -> [signtool.json](https://github.com/Akhliskun/firefox-infra-changelog/blob/master/git_files/signtool.json) - [signtool.md](https://github.com/Akhliskun/firefox-infra-changelog/blob/master/git_files/signtool.md)


For each of these repositories we save only the commits between latest release and one before. ( you can check the according .json or .md file ) From what I understood, this is the way to track these repositories.

Questions:
[1] Should we append the new release to the file when it come, or we should overwrite and keep only the latest release version?
[2] For now is it good to save all the commits from a release or we should filter them?  
[3] In the main MD table, we can save only the number of last version of the repo, to keep this table easy to read. Is it a good thing or we should add the commits?

**Comment by Akhliskun** [comment]
@raduiman Any updates on this?

**Comment by raduiman** [comment]
This issue can be closed. The code saves only the commits that are in production. 
The implemented function checks the version that is in production, compares it to the version of the build-puppet, and saves the commits from that version.
